# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title: "Asmx"
tagline:          'In two languages'
description:
    en: 'Journey of an aspiring hacker who avoids being a script kiddie..'
    tr: "Yeni yetme bir hacker'ın yolculuğu.."

baseurl:          /
